// Generated by CoffeeScript 1.7.1
(function() {
  var cfProxy, cli, help, nopt, path, utils, _;

  path = require("path");

  _ = require("underscore");

  nopt = require("nopt");

  cfProxy = require("./cf-debug-proxy");

  utils = require("./utils");

  cli = exports;

  cli.main = function(args) {
    var defValue, defValues, longOpts, name, opt, opts, parsed, shortName, shortOpts, type, _ref;
    if (args.length === 0) {
      help();
    }
    if ((_ref = args[0]) === "?" || _ref === "-?" || _ref === "--?") {
      help();
    }
    opts = {
      "break": ["b", Boolean],
      websocket: ["w", String, "__debug__"],
      verbose: ["v", Boolean],
      help: ["h", Boolean]
    };
    longOpts = {};
    shortOpts = {};
    defValues = {};
    for (name in opts) {
      opt = opts[name];
      shortName = opt[0], type = opt[1], defValue = opt[2];
      if (type === Boolean) {
        defValue = false;
      }
      shortOpts[shortName] = "--" + name;
      longOpts[name] = type;
      if (defValue != null) {
        defValues[name] = defValue;
      }
    }
    parsed = nopt(longOpts, shortOpts, args, 0);
    if (parsed.help) {
      help();
    }
    args = parsed.argv.remain;
    opts = _.pick(parsed, _.keys(longOpts));
    opts = _.defaults(opts, defValues);
    if (args.length === 0) {
      help();
    }
    utils.verbose(opts.verbose);
    cfProxy.run(args, opts);
  };

  help = function() {
    console.log("" + utils.PROGRAM + " [options] -- commmand\n\n    command      is the node command line to start your application\n\noptions:\n\n    -b --break       break at start of program (default: false)\n    -w --websocket   websocket url to expose   (default: \"__debug__\")\n    -v --verbose     be verbose\n\nThis program does the following:\n\n- starts the specified application\n  - it's PORT environment variable will be changed to port PORT+1\n  - it will be launched with the appropriate node debug option\n\n- starts a proxy server on the PORT environment variable\n\n- sends non-debug traffic (ie, not prefixed by --websocket option) to\n  the specified application\n\n- sends debug traffic (ie, prefixed by --websocket option) to the\n  v8 debug port (5858)\n\nexample:\n\n    " + utils.PROGRAM + " -b -w debug -- node server.js\n\nThis will run the command `node server.js` under debug and pause at\nthe first line of the app.\n\nversion: " + utils.VERSION + "; for more info: " + utils.HOMEPAGE);
    return process.exit(1);
  };

  if (require.main === module) {
    cli.main.call(null, process.argv.slice(2));
  }

}).call(this);
