// Generated by CoffeeScript 1.7.1
(function() {
  var cfProxy, cli, help, nopt, path, utils, _;

  path = require("path");

  _ = require("underscore");

  nopt = require("nopt");

  cfProxy = require("./cf-debug-proxy");

  utils = require("./utils");

  cli = exports;

  cli.main = function(args) {
    var debugPrefix, defValue, defValues, longOpts, name, opt, opts, parsed, shortName, shortOpts, type, _ref;
    if (args.length === 0) {
      help();
    }
    if ((_ref = args[0]) === "?" || _ref === "-?" || _ref === "--?") {
      help();
    }
    opts = {
      "break": ["b", Boolean],
      "debug-prefix": ["d", String, "--debugger"],
      verbose: ["v", Boolean],
      help: ["h", Boolean]
    };
    longOpts = {};
    shortOpts = {};
    defValues = {};
    for (name in opts) {
      opt = opts[name];
      shortName = opt[0], type = opt[1], defValue = opt[2];
      if (type === Boolean) {
        defValue = false;
      }
      shortOpts[shortName] = "--" + name;
      longOpts[name] = type;
      if (defValue != null) {
        defValues[name] = defValue;
      }
    }
    parsed = nopt(longOpts, shortOpts, args, 0);
    if (parsed.help) {
      help();
    }
    args = parsed.argv.remain;
    opts = _.pick(parsed, _.keys(longOpts));
    opts = _.defaults(opts, defValues);
    if (args.length === 0) {
      help();
    }
    utils.verbose(opts.verbose);
    debugPrefix = opts["debug-prefix"];
    if (debugPrefix === "") {
      utils.logError("the value of the --debug-prefix option must be a non-empty string");
    }
    return cfProxy.run(args, opts);
  };

  help = function() {
    console.log("" + utils.PROGRAM + " [options] -- commmand\n\n    command      is the node command line to start your application\n\noptions:\n\n  -d --debug-prefix   URL prefix of requests sent to the debugger\n  -b --break          have the debugger pause at the beginning of the program\n  -v --verbose        generate lots of diagnostic messages\n\nThis program does the following:\n\n- starts the specified application\n  - it's PORT environment variable will be changed to port PORT+1\n  - it will be launched with the appropriate node debug option\n\n- starts node-inspector on PORT+2\n\n- starts a proxy server on the PORT environment variable\n\n- sends non-debug traffic (ie, not prefixed by --debug-url option) to\n  the specified application\n\n- sends debug traffic (ie, prefixed by --debug-url option) to\n  node-inspector\n\nexample:\n\n    " + utils.PROGRAM + " -- node server.js\n\nversion: " + utils.VERSION + "; for more info: " + utils.HOMEPAGE);
    return process.exit(1);
  };

  if (require.main === module) {
    cli.main.call(null, process.argv.slice(2));
  }

}).call(this);
