// Generated by CoffeeScript 1.7.1
(function() {
  var V8Messenger, events, net, q, utils,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  net = require("net");

  events = require("events");

  q = require("q");

  utils = require("./utils");

  exports.create = function(port) {
    return new V8Messenger(port);
  };

  V8Messenger = (function(_super) {
    __extends(V8Messenger, _super);

    function V8Messenger(port) {
      this._deferred = {};
      this._seq = 1;
      this._initMessage();
      this._socket = net.connect(port);
      this._socket.setEncoding("utf8");
      this._socket.on("connect", (function(_this) {
        return function() {
          return utils.vlog("connected to v8 debugger");
        };
      })(this));
      this._socket.on("data", (function(_this) {
        return function(data) {
          return _this._onData(data);
        };
      })(this));
      this._socket.on("error", (function(_this) {
        return function(err) {
          return _this.emit("error", err);
        };
      })(this));
      this._socket.on("close", (function(_this) {
        return function() {
          utils.vlog("disconnected from v8 debugger");
          return _this.emit("close");
        };
      })(this));
    }

    V8Messenger.prototype.close = function() {
      if (this._socket == null) {
        return;
      }
      this._socket.end();
      this._socket.destroy();
      return this._socket = null;
    };

    V8Messenger.prototype.send = function(packet) {
      var packetString;
      if (this._socket == null) {
        return;
      }
      packet.type = "request";
      packet.seq = this._seq++;
      this._deferreds[packet.seq] = q.defer();
      packetString = JSON.stringify(packet);
      packetString = "Content-Length: " + packetString.length + "\r\n\r\n" + packetString;
      this._socket.write(packetString, "utf8");
      return this._deferreds[packet.seq].promise;
    };

    V8Messenger.prototype._onMessage = function(body) {
      var deferred, err, msg;
      msg = JSON.parse(body);
      if (msg.type === "event") {
        this.emit("v8-event", msg);
        return;
      }
      deferred = this._deferreds[msg.request_seq];
      if (deferred == null) {
        return;
      }
      delete this._deferreds[msg.request_seq];
      if (msg.success) {
        deferred.resolve(msg);
        return;
      }
      err = new Error(msg.message);
      err.isV8 = true;
      return deferred.reject(err);
    };

    V8Messenger.prototype._onData = function(data) {
      var body, delim, key, line, val;
      if (this._socket == null) {
        return;
      }
      this.buffer += data;
      while (true) {
        if (!this.inHeaders) {
          if (this.buffer.length < this.contentLength) {
            return;
          }
          body = this.buffer.substr(0, this.contentLength);
          this.buffer = this.buffer.substr(this.contentLength);
          this._onMessage(body);
          this._initMessage();
          continue;
        }
        delim = this.buffer.indexOf("\r\n");
        if (-1 === delim) {
          return;
        }
        line = this.buffer.substr(line, delim);
        this.buffer = this.buffer.substr(delim + 2);
        if (line === "") {
          this.inHeaders = false;
          continue;
        }
        delim = line.indexOf(":");
        if (-1 === delim) {
          key = line;
          val = "";
        } else {
          key = (line.substr(0, delim)).trim();
          val = (line.substr(delim + 1)).trim();
        }
        this.headers[key] = val;
        if (key === "Content-Length") {
          this.contentLength = parseInt(val, 10);
        }
      }
    };

    return V8Messenger;

  })(events.EventEmitter);

}).call(this);
